# -*- coding: utf-8 -*-
"""SVM to classify images

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vkj4m62yZdIG9BV7HriXMOYF7gVwoRNQ
"""

from google.colab import files
uploaded = files.upload()

import zipfile

with zipfile.ZipFile("dogs-vs-cats.zip", "r") as zip_ref:
    zip_ref.extractall()

print("Dataset Extracted Successfully!")

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

train_cat = "training_set/training_set/cats"
train_dog = "training_set/training_set/dogs"

test_cat = "test_set/test_set/cats"
test_dog = "test_set/test_set/dogs"

IMG_SIZE = 64

X = []
y = []

limit = 1000

count = 0

for img in os.listdir(train_cat):

    if img.startswith("."):
        continue

    if count >= limit:
        break

    path = os.path.join(train_cat, img)

    image = cv2.imread(path)

    if image is None:
        continue

    image = cv2.resize(image, (IMG_SIZE, IMG_SIZE))
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    X.append(image.flatten())

    y.append(0)

    count += 1

count = 0

for img in os.listdir(train_dog):

    if img.startswith("."):
        continue

    if count >= limit:
        break

    path = os.path.join(train_dog, img)

    image = cv2.imread(path)

    if image is None:
        continue

    image = cv2.resize(image, (IMG_SIZE, IMG_SIZE))
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    X.append(image.flatten())

    y.append(1)

    count += 1

X = np.array(X, dtype=np.float32) / 255.0
y = np.array(y)

print(X.shape)
print(y.shape)

X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

svm = SVC(
    kernel="rbf",
    C=10,
    gamma="scale"
)

svm.fit(X_train, y_train)

y_pred = svm.predict(X_val)

print("Accuracy:", accuracy_score(y_val, y_pred))

print(classification_report(y_val, y_pred))

print(classification_report(y_val, y_pred))

cm = confusion_matrix(y_val, y_pred)

print(cm)

plt.figure(figsize=(12,10))

for i in range(9):

    plt.subplot(3,3,i+1)

    img = X_val[i].reshape(64,64,3)

    plt.imshow(img)

    actual = "Cat" if y_val[i]==0 else "Dog"
    pred = "Cat" if y_pred[i]==0 else "Dog"

    plt.title(f"Actual:{actual}\nPred:{pred}")

    plt.axis("off")

plt.show()

X_test = []
y_test = []

for img in os.listdir(test_cat):

    if img.startswith("."):
        continue

    path = os.path.join(test_cat, img)

    image = cv2.imread(path)

    if image is None:
        continue

    image = cv2.resize(image,(64,64))
    image = cv2.cvtColor(image,cv2.COLOR_BGR2RGB)

    X_test.append(image.flatten())

    y_test.append(0)

for img in os.listdir(test_dog):

    if img.startswith("."):
        continue

    path = os.path.join(test_dog, img)

    image = cv2.imread(path)

    if image is None:
        continue

    image = cv2.resize(image,(64,64))
    image = cv2.cvtColor(image,cv2.COLOR_BGR2RGB)

    X_test.append(image.flatten())

    y_test.append(1)

X_test = np.array(X_test, dtype=np.float32) / 255.0
y_test = np.array(y_test)

test_pred = svm.predict(X_test)

print("Test Accuracy:", accuracy_score(y_test, test_pred))

print(classification_report(y_test, test_pred))

plt.figure(figsize=(12,12))

for i in range(16):

    plt.subplot(4,4,i+1)

    plt.imshow(X_test[i].reshape(64,64,3))

    label = "Cat" if test_pred[i]==0 else "Dog"

    plt.title(label)

    plt.axis("off")

plt.show()

print("Training Accuracy:", svm.score(X_train, y_train))

print("Test Accuracy:", accuracy_score(y_test, test_pred))

print(classification_report(y_test, test_pred))

print(confusion_matrix(y_test, test_pred))

plt.figure(figsize=(12,12))

for i in range(16):

    plt.subplot(4,4,i+1)

    plt.imshow(X_test[i].reshape(64,64,3))

    actual = "Cat" if y_test[i] == 0 else "Dog"
    predicted = "Cat" if test_pred[i] == 0 else "Dog"

    plt.title(f"Actual: {actual}\nPred: {predicted}")

    plt.axis("off")

plt.tight_layout()
plt.show()

print("Training Accuracy:", svm.score(X_train, y_train))
print("Test Accuracy:", accuracy_score(y_test, test_pred))

print(classification_report(y_test, test_pred))

print(confusion_matrix(y_test, test_pred))

plt.figure(figsize=(12,12))

for i in range(16):
    plt.subplot(4,4,i+1)
    plt.imshow(X_test[i].reshape(64,64,3))

    actual = "Cat" if y_test[i] == 0 else "Dog"
    predicted = "Cat" if test_pred[i] == 0 else "Dog"

    color = "green" if actual == predicted else "red"

    plt.title(f"Actual: {actual}\nPred: {predicted}",
              color=color, fontsize=10)

    plt.axis("off")

plt.tight_layout()
plt.show()

print("Training Accuracy:", svm.score(X_train, y_train))
print("Testing Accuracy:", accuracy_score(y_test, test_pred))

from sklearn.metrics import classification_report

print(classification_report(y_test, test_pred))

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, test_pred)
print(cm)

import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

ConfusionMatrixDisplay.from_predictions(
    y_test,
    test_pred,
    display_labels=["Cat", "Dog"],
    cmap="Blues"
)

plt.title("Confusion Matrix")
plt.show()